# Generated by Django 4.2.5 on 2023-09-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(null=True, verbose_name='Tarih - Saat'),
        ),
    ]
